### ISSUE TITLE
update to 0.12.1

### ISSUE THREAD

**Issue by iGom** [libretro/SameBoy#33]
Since Jun 22, the emulator SameBoy was updated with several improvements and it would be interesting to update the core of libretro as well which is 0.11.2 at the moment.

**Comment by Dogway** [comment]
[0.12.2](https://sameboy.github.io/posts/release-0.12.2) Fixed audio on libretro, which I can attest.

**Comment by ghost** [comment]
@iGom @Dogway 

This core is built recently (19-10-06) and contains most if not all changes from the upstream branch (Thanks go to Awakened from the Libretro forums)

[sameboy_libretro.zip](https://github.com/libretro/SameBoy/files/3706983/sameboy_libretro.zip)

**Comment by gouchi** [comment]
- [Issue](https://github.com/libretro/libretro-super/issues/1123) on libretro-super repository.

**Comment by hizzlekizzle** [comment]
It's been updated for quite some time, so I'm gonna close this.
