### ISSUE TITLE
Incomplete memory mapping for achievements

### ISSUE THREAD

**Issue by Sanaki** [libretro/SameBoy#43]
I'm unsure if this needs to be addressed on the libretro end or in upstream. Numerous games have large sections of achievements unsupported due to SameBoy not exposing memory fully. One such example is Kirby's Dream Land 2, but in my experience a solid half or more of the games with achievement sets can't activate the full set. This is particularly disheartening when dealing with SGB-enhanced games, which no other core can make look even halfway decent.

Corresponding upstream issue: https://github.com/LIJI32/SameBoy/issues/227

**Comment by iGom** [comment]
Same issue in Super Mario Land 2: 6 Golden Coins, only one achievement is supported.

**Comment by negativeExponent** [comment]
it should work with this, https://github.com/negativeExponent/SameBoy/commit/84d95453d9b0d953222d536b7aa76334c588860a

basically, this moves memory mappings out of init_for_current_model(), and delay the mappings right before the end of retro_load_game()

this means that memory map will work on the first core (non-multiplayer mode) only but i dont think mem map is working at all for the separate cores.

the issue was that memory mapping are happening before loading rom, which invalidates cheevos when rom map returns NULL

haven't had time to test this but mapping looks OK:

```
[libretro INFO] Rumble environment supported
[INFO] [Environ]: GET_VARIABLE sameboy_color_correction_mode:
	emulate hardware
[INFO] [Environ]: GET_VARIABLE sameboy_rumble:
	rumble-enabled games
[INFO] [Environ]: GET_VARIABLE sameboy_high_pass_filter_mode:
	accurate
[INFO] [Environ]: GET_VARIABLE sameboy_model:
	Auto
[INFO] [Environ]: GET_VARIABLE sameboy_border:
	Super Game Boy only
[INFO] [Environ]: SET_MEMORY_MAPS.
[INFO]    ndx flags  ptr              offset   start    select   disconn  len      addrspace
[INFO]    001 M1A1bc 0x7ffbf2116a35 00000000 0000FFFF FFFFFFFF 00000000 00000001 
[INFO]    002 M1A1bc 0x7ffbf211eac0 00000000 0000FF80 FFFFFF80 00000000 00000080 
[INFO]    003 M1A1bc 0x5635a959bc40 00000000 0000C000 FFFFF000 00000000 00001000 
[INFO]    004 M1A1bc 0x5635a959cc40 00000000 0000D000 FFFFF000 00000000 00001000 
[INFO]    005 M1A1bc 0x5635a98851e0 00000000 0000A000 FFFFE000 00000000 00002000 
[INFO]    006 M1A1bc 0x5635a98831d0 00000000 00008000 FFFFE000 00000000 00002000 
[INFO]    007 M1A1bC 0x5635a862d820 00000000 00000000 FFFFC000 00000000 00004000 
[INFO]    008 M1A1bC 0x5635a8631820 00000000 00004000 FFFFC000 00000000 00004000 
[INFO]    009 M1A1bc 0x7ffbf211ec75 00000000 0000FE00 FFFFFF00 00000000 000000A0 
[INFO]    010 M1A1bc 0x5635a959dc40 00000000 00010000 FFFF0000 00000000 00010000 
[INFO]    011 M1A1bc 0x7ffbf211eb3f 00000000 0000FF00 FFFFFF00 00000000 00000080 
[INFO] Skipping SRAM load..
[INFO] Version of libretro API: 1
[INFO] Compiled against API: 1
[INFO] [Cheats]: Load game-specific cheatfile: /home/negative/.config/retroarch/cheats/SameBoy/Super Mario Land 2 - 6 Golden Coins (USA, Europe).cht
[INFO] [Audio]: Set audio input rate to: 384000.00 Hz.
```

**Comment by negativeExponent** [comment]
this should already be working, right?

**Comment by Sanaki** [comment]
Yeah, forgot to close it. We're all good now.
