### ISSUE TITLE
Can't load ROM files with special characters in filename.

### ISSUE THREAD

**Issue by TheSkidd** [libretro/SameBoy#52]
If I try to load a ROM file with the word Pokémon in it, the core will fail to start up. If I rename the same file to say Pokemon then it will load normally. Standalone SameBoy can load the file even if it has a special character in its name.

**Comment by hug0b** [comment]
I can confirm I can't load a ROM with accents in the path. Moving the same ROM to Desktop, I could load it.

```
Could not open ROM: No such file or directory.
[libretro INFO] Failed to load ROM at C:\Games\Shin Pok├⌐mon Red and Blue\test\Tetris 2 (USA, Europe) (SGB Enhanced).gb
```
